Add spacing between sections, Center and insert captions for all images
CS2103JAN2017-W14-B4/main pull request #91
Opened 2017-03-17 22:04 UTC by robinloh

2017-03-19 06:20 UTC, jtlx requested changes
Thanks for the edits!

Might want to standardize the line spacing after H2 headings ('##'). Varies a bit between files.

2017-03-19 06:20 UTC, JTLX commented on docs/UsingGithubPages.md
Should there be a \<br\> here to match other level 2 headings?

2017-03-21 18:42 UTC, jtlx approved these changes

2017-03-22 03:22 UTC, robinloh commented on docs/UsingGithubPages.md
Ok added!

2017-03-22 04:43 UTC, merged